### PR TITLE
Fix #52, #21 and #35

### LINKED ISSUE #52: setting "verify: true" is causing alexa app to timeout from echo devices
When I set the flag for verify to be true it works when I try to check my endpoint from a non-echo device.  It properly returns a 401 error message:

```
{
  "status": "failure",
  "reason": "The signaturecertchainurl HTTP request header is invalid!"
}
```

However, when I try to test the app from the Amazon Alexa dev website or any echo devices, it throws an error that the requested skill has taken too long to respond.

Switching the flag back to false or removing completely and it goes back to working from echo devices but obviously it is going to fail certification.

### PR DESCRIPTION
**Pull request by dblock**
@mreinstein correctly calls that #54 fixes #52, #21 and partially #35. What this does is use alexa-app's `express` method instead of cooking our own, plus a test that right now would hang on master and no longer hangs in this branch.

Replaces https://github.com/alexa-js/alexa-app-server/pull/56 on top of #60.

This is dependent on https://github.com/alexa-js/alexa-app/pull/150, I didn't find a better way to get `?utterances`, `?schema` and `preRequest` and `postRequest` support without moving this logic upstream to alexa-app.

### CODE REVIEW

**Comment by dblock** [comment]
Thanks for checking it out @rickwargo. I'll wait for @tejashah88 to do a code review of this and the upstream PR and merge. We should get things sorted out with a release next. Do you have anything blocking and not working after this?

**Comment by rickwargo** [comment]
@dblock on the surface it appears all good, but haven't had the time to dig under the covers. i'll have more time tomorrow.

File: index.js [hunk 1]
```diff
@@ -6,346 +6,298 @@ var https = require('https');
...
+
+  self.start = function() {
+    // Instantiate up the server
+    // TODO: add i18n support (i18n-node might be a good look)
+    // Issue #12: https://github.com/alexa-js/alexa-app-server/issues/12
+    self.express = express();
+
+    // TODO: change this to make sure it doesn't affect other non-Alexa services/apps
+    // Issue #35: https://github.com/alexa-js/alexa-app-server/issues/35
+    self.express.use(bodyParser.urlencoded({ extended: true }));
```
Comment (tejashah88) [inline index.js]: According to [this](https://github.com/alexa-js/alexa-app-server/pull/18#issuecomment-273465357) comment in #18, shouldn't it be this:
```javascript
self.express.use("/alexa", bodyParser.urlencoded({ extended: true }));
```
#35 stated that "there are many express routes added which don't use urlencoded forms". So logically, one would want to only bind with Alexa-based routes.

Comment (dblock) [inline index.js]: Yes, but that issue is still open, I didn't get a chance to write a test for that and fix it. There were tabs->spaces changes here so it looks like this has changed, but it has not. You can look at the diff without spaces, https://github.com/alexa-js/alexa-app-server/pull/64/files?w=1

**Comment by dblock** [comment]
I've updated this with a fix for #35. Now that we're mounting body-parser inside alexa-app, we can just remove it from alexa-app-server. See https://github.com/alexa-js/alexa-app/pull/155 for details.

@tejashah88 this is ready for you to merge

File: package.json [hunk 2]
```diff
@@ -19,7 +19,7 @@
   },
   "license": "MIT",
   "dependencies": {
-    "alexa-app": "^2.4.0",
+    "alexa-app": "alexa-js/alexa-app",
```
Comment (dblock) [inline package.json]: Once we've released 2.4.0 I'll change this and make a release of alexa-app-server.

**Comment by rickwargo** [comment]
Sorry, @tejashah88, didn't get a chance to review today. I will have time in the morning.

**Comment by rickwargo** [comment]
Looks good, however bodyParser.urlencoded() is now removed via alexa-app#152 - found this testing a form post hosted in alexa-app-server. I believe this was previously handled - does it need to be handled or should it be called out in the README?

**Comment by rickwargo** [comment]
One (simple) formatting suggestion is to remove trailing slashes from the `normalizedRoot` in `self.loadapps()`. The comments have an example where the server root ends with a slash and if included, the message says, "loaded app [hello_world] at endpoint: /alexa//hello_world."

**Comment by dblock** [comment]
I think the urlencoded bodyparser is not the business of these libraries. I've added a note to UPGRADING in https://github.com/alexa-js/alexa-app/pull/158.

Opened https://github.com/alexa-js/alexa-app-server/issues/68 for the slashes thing, it's cosmetic unless I'm missing something.

**Comment by dblock** [comment]
Looks like everyone is happy with this, merging. Thanks for your help!

**Comment by rickwargo** [comment]
@dblock cosmetic only. I'm fine either way on the urlencoded bodyparser - #64 breaks functionality so it needs to be noted. Could be I was the only one using that.

**Comment by dblock** [comment]
Yep @rickwargo, I documented this change in UPGRADING, both here (https://github.com/alexa-js/alexa-app-server/pull/69) and alexa-app (https://github.com/alexa-js/alexa-app/pull/158).
